<?php
/**
 * Export the local Elementor content into a portable data file for the prod
 * importer (Bluehost has no WP-CLI). Captures, for each marketing page + the
 * header/footer library templates: _elementor_data (base64), _elementor_page_settings,
 * _elementor_template_type, _elementor_version, _elementor_edit_mode. Plus the active
 * Kit's global colors/fonts (_elementor_page_settings), the elementor_* experiment
 * options, and the Primary nav menu. URLs are NOT rewritten here — the importer does
 * the localhost -> prod replacement so the file stays host-portable.
 *
 * Run: docker compose run --rm -T wpcli wp eval-file /scripts/wp/elementor/export-for-prod.php
 * Output: /var/www/html/wp-content/themes/buckleup/.. no — writes to /scripts dist below.
 */
global $wpdb;

$PAGE_IDS = array( 38, 39, 40, 41, 42, 44, 45 );
$TEMPLATES = array(
	163 => array( 'title' => 'Site Header', 'name' => 'site-header' ),
	164 => array( 'title' => 'Site Footer', 'name' => 'site-footer' ),
);
$KIT_ID = (int) get_option( 'elementor_active_kit' );

$meta_keys = array( '_elementor_data', '_elementor_page_settings', '_elementor_template_type', '_elementor_version', '_elementor_edit_mode' );

$grab = static function ( $id ) use ( $wpdb, $meta_keys ) {
	$out = array();
	foreach ( $meta_keys as $k ) {
		$v = $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id=%d AND meta_key=%s", $id, $k ) );
		if ( null !== $v ) {
			$out[ $k ] = base64_encode( $v );
		}
	}
	return $out;
};

$data = array( 'posts' => array(), 'templates' => array(), 'kit' => array(), 'options' => array(), 'menu' => array() );

foreach ( $PAGE_IDS as $id ) {
	$data['posts'][ $id ] = $grab( $id );
}
foreach ( $TEMPLATES as $id => $info ) {
	$row = $grab( $id );
	$row['_title'] = $info['title'];
	$row['_name']  = $info['name'];
	$data['templates'][ $id ] = $row;
}

// Kit globals — read RAW stored bytes (the value is a serialized array; no cast).
$kit_ps = $wpdb->get_var( $wpdb->prepare( "SELECT meta_value FROM {$wpdb->postmeta} WHERE post_id=%d AND meta_key='_elementor_page_settings'", $KIT_ID ) );
$data['kit'] = array(
	'src_id'        => $KIT_ID,
	'title'         => get_the_title( $KIT_ID ),
	'name'          => get_post_field( 'post_name', $KIT_ID ),
	'page_settings' => base64_encode( (string) $kit_ps ),
);

// Elementor options to replicate (experiments + a few settings)
$opt_rows = $wpdb->get_results( "SELECT option_name, option_value FROM {$wpdb->options} WHERE option_name LIKE 'elementor\_experiment-%' OR option_name IN ('elementor_active_kit','elementor_font_display','elementor_css_print_method','elementor_disable_color_schemes','elementor_disable_typography_schemes','elementor_cpt_support','elementor_global_image_lightbox','elementor_load_fa4_shim','elementor_optimized_image_loading','elementor_optimized_gutenberg_loading','elementor_lazy_load_background_images')" );
foreach ( $opt_rows as $r ) {
	$data['options'][ $r->option_name ] = $r->option_value;
}

// Primary menu (term 51) + items
$menu = wp_get_nav_menu_object( 'Primary' );
if ( $menu ) {
	$items = wp_get_nav_menu_items( $menu->term_id );
	$mi = array();
	foreach ( (array) $items as $it ) {
		$mi[] = array(
			'title'  => $it->title,
			'url'    => $it->url,
			'type'   => $it->type,        // custom / post_type / taxonomy
			'object' => $it->object,      // page / custom
			'object_id' => (int) $it->object_id,
			'order'  => (int) $it->menu_order,
		);
	}
	$data['menu'] = array( 'name' => $menu->name, 'slug' => $menu->slug, 'items' => $mi );
}

$php = "<?php\n/** AUTO-GENERATED by export-for-prod.php. Elementor content for prod import. */\nreturn " . var_export( $data, true ) . ";\n";

// /scripts is read-only in the container, so emit to STDOUT between markers; the
// host captures it. Summary line goes to STDERR so it doesn't pollute the file.
fwrite( STDERR, "Exported " . count( $data['posts'] ) . " pages, " . count( $data['templates'] ) . " templates, kit src_id={$data['kit']['src_id']}, " . count( $data['options'] ) . " options, menu items=" . count( $data['menu']['items'] ?? array() ) . "\n" );
echo "===BU_DATA_START===\n";
echo $php;
echo "===BU_DATA_END===\n";
