<?php
/**
 * Question-bank seed.
 *
 * Single source of truth for the bank is the committed data files:
 *   - includes/data/questions-verified.php  (Q1-Q35 from the source PDF, with its
 *     published answer key — generated by scripts/wp/quiz/parse-verified.py)
 *   - includes/data/questions-authored.php  (BuckleUp-authored, BC/ICBC-accurate
 *     questions covering all 12 categories)
 *
 * Seeding is idempotent: rows upsert on the unique `source_ref`, so re-running
 * never duplicates and any correction to a data file applies on the next run.
 * This mirrors the locations/testimonials seed-from-data-file workflow and is
 * how the bank ships to the shell-less prod host (token-PHP helper calls this).
 *
 * @package BuckleUp_Quiz
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Load and merge the question data files.
 *
 * @return array<int,array<string,mixed>>
 */
function buckleup_quiz_load_seed_data() {
	$rows  = array();
	$files = array(
		BUCKLEUP_QUIZ_PATH . 'includes/data/questions-verified.php',
		BUCKLEUP_QUIZ_PATH . 'includes/data/questions-authored.php',
	);
	foreach ( $files as $file ) {
		if ( file_exists( $file ) ) {
			$data = include $file;
			if ( is_array( $data ) ) {
				$rows = array_merge( $rows, $data );
			}
		}
	}
	return $rows;
}

/**
 * Validate + normalise a single question row. Returns the clean row or null.
 *
 * @param array<string,mixed> $row
 * @return array<string,mixed>|null
 */
function buckleup_quiz_normalise_row( $row ) {
	if ( ! is_array( $row ) ) {
		return null;
	}
	$source_ref = isset( $row['source_ref'] ) ? sanitize_text_field( (string) $row['source_ref'] ) : '';
	$category   = isset( $row['category'] ) ? sanitize_key( (string) $row['category'] ) : '';
	$question   = isset( $row['question'] ) ? trim( wp_strip_all_tags( (string) $row['question'] ) ) : '';
	$options    = array(
		isset( $row['option_a'] ) ? trim( wp_strip_all_tags( (string) $row['option_a'] ) ) : '',
		isset( $row['option_b'] ) ? trim( wp_strip_all_tags( (string) $row['option_b'] ) ) : '',
		isset( $row['option_c'] ) ? trim( wp_strip_all_tags( (string) $row['option_c'] ) ) : '',
		isset( $row['option_d'] ) ? trim( wp_strip_all_tags( (string) $row['option_d'] ) ) : '',
	);
	$correct = isset( $row['correct_index'] ) ? (int) $row['correct_index'] : -1;

	// Hard requirements: a stable ref, a known category, a question, four
	// non-empty options, and a correct index in range.
	if ( '' === $source_ref || '' === $question ) {
		return null;
	}
	if ( ! buckleup_quiz_is_category( $category ) ) {
		return null;
	}
	foreach ( $options as $opt ) {
		if ( '' === $opt ) {
			return null;
		}
	}
	if ( $correct < 0 || $correct > 3 ) {
		return null;
	}

	$difficulty = isset( $row['difficulty'] ) ? (int) $row['difficulty'] : 2;
	$difficulty = max( 1, min( 3, $difficulty ) );

	return array(
		'source_ref'    => $source_ref,
		'category'      => $category,
		'question'      => $question,
		'option_a'      => $options[0],
		'option_b'      => $options[1],
		'option_c'      => $options[2],
		'option_d'      => $options[3],
		'correct_index' => $correct,
		'explanation'   => isset( $row['explanation'] ) ? trim( wp_strip_all_tags( (string) $row['explanation'] ) ) : '',
		'difficulty'    => $difficulty,
	);
}

/**
 * Seed (insert/upsert) the question bank from the data files. Idempotent.
 *
 * @return array{inserted:int,updated:int,skipped:int,total_active:int}
 */
function buckleup_quiz_seed_questions() {
	global $wpdb;
	$table = buckleup_quiz_table( 'questions' );
	$now   = current_time( 'mysql', true );

	$inserted = 0;
	$updated  = 0;
	$skipped  = 0;
	$seen     = array();

	foreach ( buckleup_quiz_load_seed_data() as $raw ) {
		$row = buckleup_quiz_normalise_row( $raw );
		if ( null === $row ) {
			++$skipped;
			continue;
		}
		// Guard against duplicate source_refs within the data files themselves.
		if ( isset( $seen[ $row['source_ref'] ] ) ) {
			++$skipped;
			continue;
		}
		$seen[ $row['source_ref'] ] = true;

		$existing_id = $wpdb->get_var(
			$wpdb->prepare( "SELECT id FROM {$table} WHERE source_ref = %s", $row['source_ref'] )
		);

		$data    = array(
			'category'      => $row['category'],
			'question'      => $row['question'],
			'option_a'      => $row['option_a'],
			'option_b'      => $row['option_b'],
			'option_c'      => $row['option_c'],
			'option_d'      => $row['option_d'],
			'correct_index' => $row['correct_index'],
			'explanation'   => $row['explanation'],
			'difficulty'    => $row['difficulty'],
			'updated_at'    => $now,
		);
		$formats = array( '%s', '%s', '%s', '%s', '%s', '%s', '%d', '%s', '%d', '%s' );

		if ( $existing_id ) {
			$wpdb->update( $table, $data, array( 'id' => (int) $existing_id ), $formats, array( '%d' ) );
			++$updated;
		} else {
			$data['source_ref'] = $row['source_ref'];
			$data['is_active']  = 1;
			$data['created_at'] = $now;
			$insert_formats     = array_merge( $formats, array( '%s', '%d', '%s' ) );
			$wpdb->insert( $table, $data, $insert_formats );
			++$inserted;
		}
	}

	$total_active = (int) $wpdb->get_var( "SELECT COUNT(*) FROM {$table} WHERE is_active = 1" );

	return array(
		'inserted'     => $inserted,
		'updated'      => $updated,
		'skipped'      => $skipped,
		'total_active' => $total_active,
	);
}

/**
 * Per-category active-question counts (used by selection guards + the admin/QA
 * verification step).
 *
 * @return array<string,int> slug => count
 */
function buckleup_quiz_category_counts() {
	global $wpdb;
	$table = buckleup_quiz_table( 'questions' );
	$rows  = $wpdb->get_results( "SELECT category, COUNT(*) AS c FROM {$table} WHERE is_active = 1 GROUP BY category", ARRAY_A );
	$out   = array();
	foreach ( (array) $rows as $r ) {
		$out[ $r['category'] ] = (int) $r['c'];
	}
	return $out;
}
